import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import '@fontsource/poppins';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '3D Bot by puneethx',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-black' style={{fontFamily:"Poppins"}}>{children}</body>
    </html>
  )
}
